### ISSUE TITLE
Acknowledge Pachi?

### ISSUE THREAD

**Issue by pasky** [facebookresearch/darkforestGo#1]
Hi! I'm glad you found Pachi useful when developing darkforest. It seems to me that besides the unused-by-default pachi-tactics/ code, pieces of the board/ code also were inspired by Pachi, in the pattern and policy modules in particular, is that a correct impression?

I _don't_ think what you did is a licence problem wrt. GPL or anything, for a variety of specific reasons. I'm happy it helped.  But if you agree that a mention in the README near the bottom like "Some portions of the tactics and pattern code were inspired by the Pachi engine." would be appropriate, I'd be glad to see it mentioned. :-)

**Comment by yuandong-tian** [comment]
Hi Petr,

Sorry for the confusion. The initial DF code was indeed inspired by Pachi
(Thanks you very much!). Currently it uses its own pattern library in
patternv2.c, and hence does not rely on pachi code. But I agree there is a
confusion by putting pattern.c in the ./board directory. I will clean it up
and put the line you suggested in the README.md file.

Best,
Yuandong

On Fri, Jun 10, 2016 at 11:21 AM, Petr Baudis notifications@github.com
wrote:

> Hi! I'm glad you found Pachi useful when developing darkforest. It seems
> to me that besides the unused-by-default pachi-tactics/ code, pieces of the
> board/ code also were inspired by Pachi, in the pattern and policy modules
> in particular, is that a correct impression?
> 
> I don't think what you did is a licence problem wrt. GPL or anything, for
> a variety of specific reasons. I'm happy it helped. But if you agree that a
> mention in the README near the bottom like "Some portions of the tactics
> and pattern code were inspired by the Pachi engine." would be appropriate,
> I'd be glad to see it mentioned. :-)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/facebookresearch/darkforestGo/issues/1, or mute the
> thread
> https://github.com/notifications/unsubscribe/AC1g8WeilpqK7bJ5t1VBpiQpSpWmASuHks5qKas3gaJpZM4IzMuX
> .

## 

---

Yuandong Tian
Research Scientist,
Facebook Artificial Intelligence Research (FAIR)
Website:
https://research.facebook.com/researchers/1517678171821436/yuandong-tian/

**Comment by yuandong-tian** [comment]
Done. README.md updated.

**Comment by pasky** [comment]
Thank you!!
