### ISSUE TITLE
Unclear dependencies in readme

### ISSUE THREAD

**Issue by tommituura** [facebookresearch/darkforestGo#2]
Hi, 

I'm trying to follow the instructions to install the dependencies:
1. Install torch7.
2. Install luarocks: class, image, tds, cudnn

But none of those luarocks can be found, at least on luarocks.org, AFAICT:
https://luarocks.org/search?q=class
https://luarocks.org/search?q=image
https://luarocks.org/search?q=tds
https://luarocks.org/search?q=cudnn

Please bear in mind I have absolutely zero experience with Lua or Luarocks, I'm a python/ruby coder mostly. I might very well just be ignorant of some basic information every Lua coder knows by heart that has been omitted as "obvious".

**Comment by yzhuuu** [comment]
Hi tommituura,

My suggestion is to follow the instruction here:
http://torch.ch/docs/getting-started.html#_

Make sure you have torch installed, then install dependencies using luarocks.

**Comment by apetresc** [comment]
The problem isn't getting luarocks installed, it's that there are no luarocks modules with those names (`class`, `image`, `tds`, or `cudnn`).

**Comment by soumith** [comment]
@apetresc if you specifically install torch, and invoke the luarocks that is shipped with torch, then those packages are available. We host our own rocks server here: https://github.com/torch/rocks

**Comment by apetresc** [comment]
Ah, gotcha! That explains it, thanks :)
