### ISSUE TITLE
dropbox连不上，无法获取models

### ISSUE THREAD

**Issue by jzcyz** [facebookresearch/darkforestGo#22]
求好心人给传一份，多谢多谢。

**Comment by yuandong-tian** [comment]
http://yuandong-tian.com/df_models/

**Comment by jzcyz** [comment]
收到，多谢

李翼    56435521
yli@travelsky.com

发件人： Yuandong Tian
发送时间： 2016-10-28 01:25
收件人： facebookresearch/darkforestGo
抄送： jzcyz; Author
主题： Re: [facebookresearch/darkforestGo] dropbox连不上，无法获取models (#22)
http://yuandong-tian.com/df_models/
