### ISSUE TITLE
Can not setup_board

### ISSUE THREAD

**Issue by teddy960370** [facebookresearch/darkforestGo#24]
from Readme.md
`th cnnPlayerMCTSV2.lua [other_options] --setup_board "/path/to/sgf 23"`

I used it but it has some error

bio1607b@bio1607b-MS-7817:~/Downloads/darkforestGo/cnnPlayerV2$ th cnnPlayerMCTSV2.lua --save_sgf_per_move --num_gpu 1 --pipe_path /home/bio1607b/Downloads/darkforestGo/local_evaluator --setup_board "/home/bio1607b/Downloads/darkforestGo/cnnPlayerV2/18760408.sgf 12"
Pattern file ../models/playout-model.bin loaded!
CNNPlayerV2MCTSParams is NULL, set default parameters.
Pattern file ../models/playout-model.bin loaded!
---- PatternV2 -----
#hash_size: 1048576, NUM_PRIOR: 17, LEN_PRIOR: 49
Verbose: 1, cnt_threshold: 1, alpha: 0.015000, batch_size: 8, temperature: 0.125000, ply_fraction: 0.001000
neighbor: true, nakade: true, resp: true, save_atari: true, kill_other: true, global: false, ko: true, put_group_to_atari: true, eye: true
#Pattern: 754901, collision: 198968663
Sample from topn: -1
-- End Patternv2 ---
New MCTS game, signature: 2016-11-15_17-24-48 ------------ Parameters for Search -----------------
Local Pipe path: /home/bio1607b/Downloads/darkforestGo/local_evaluator
Verbose: 1
PrintSearchTree: false
#GPU: 1
#Use CPU rollout only: false
Komi: 6.5
dynkomi_factor: 0.00
Rule: chinese
Use heuristic time management: 0, max_time_spent: 0.000000, min_time_spent: 0.000000
+++++++++++ Tree #0 ++++++++++++
Verbose: 1
#Threads: 16
#Receivers: 1
Sigma: 0.05, over n: false
Async mode: false
RAVE: false
UCT: PUCT
num_rollout: 1000
num_rollout_per_move: 1000
num_playout_per_rollout: 1
num_rollout_peekable: 20000
num_dcnn_per_move: 1000
rcv_acc_percent_thres: 80
rcv_max_num_move: 20
rcv_min_num_move: 1
expand_n_thres: 0
decision_mixture_ratio: 5.0
Use pondering: false
Time limit: 0
% of threads running playout when expanding node: 0
single_move_return: false
default_policy: PATTERN_V2 [-1, T: 0.125]
+++++++++++ End Tree ++++++++++++
 --------- End parameters for Search --------------
/home/bio1607b/torch/install/bin/luajit: ../cnnPlayerV2/cnnPlayerV2Framework.lua:216: attempt to concatenate local 'donnot_flip_vertical' (a boolean value)
stack traceback:
	../cnnPlayerV2/cnnPlayerV2Framework.lua:216: in function 'setup_board'
	../cnnPlayerV2/cnnPlayerV2Framework.lua:877: in function '__init'
	/home/bio1607b/torch/install/share/lua/5.1/class/init.lua:164: in function 'CNNPlayerV2'
	cnnPlayerMCTSV2.lua:336: in main chunk
	[C]: in function 'dofile'
	...607b/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
Segmentation fault (core dumped)

**Comment by yuandong-tian** [comment]
Bug fixed.
