### ISSUE TITLE
Cannot open pipe /data/local/go//./pipe-0-0 (client) !

### ISSUE THREAD

**Issue by yuchenlin** [facebookresearch/darkforestGo#27]
I do have started the server and I have tried to use another directory as pipe. But it's always like this when I type  clear_board

> bill@Darkstar:~/fbgo/darkforestGo/cnnPlayerV2$ th cnnPlayerMCTSV2.lua
> Pattern file ../models/playout-model.bin loaded!
> CNNPlayerV2MCTSclear_board
> Cannot open pipe /data/local/go//./pipe-0-0 (client) !
> /home/kangqi/workspace/distro/install/bin/luaji

**Comment by yuchenlin** [comment]
Sorry, it's a simple permission problem

**Comment by ofekih** [comment]
How'd you fix this?

**Comment by ofekih** [comment]
The contents of my cnn_eval-1.log are:

cnn_evaluator.sh: 23: cnn_evaluator.sh: th: not found

**Comment by devanshpgupta** [comment]
Hi yuchenlin, Can you please tell what permission problem is it and how can we fix it???
Would appreciate your help .
Thanx

**Comment by devanshpgupta** [comment]
Can You please explain how to fix the problem or what the actual problem is???
Would really appreciate the help.

**Comment by WuSiying315** [comment]
I have the same problem as you. How did you solve it?

**Comment by kxxwz** [comment]
This problem is caused by not specifying "pipe_path".
`th cnnPlayerMCTSV2.lua --pipe_path ../data/local/go` will work.
