### ISSUE TITLE
System requirement and GTP setup

### ISSUE THREAD

**Issue by aniljava** [facebookresearch/darkforestGo#3]
I tested Tested cnnPlayerMCTSV2.lua on 750 Ti, it responded normally upto 6 moves, after that it stopped responding and started freezing computer.

Also, when using cnnPlayerMCTSV2.lua with gogui, the debug messages with line ends, i think interferes with the GTP protocol triggering the timeout on the gogui.

A guide on GTP setup and expected system requirement would be nice.

**Comment by yuandong-tian** [comment]
How many GPUs do you use? In my case, I tested 1 and 4 GPUs and it works fine.

Did you set the time limit? --time_limit 10 will restrict the time usage to
10-11 sec.

I have not tried using it with gogui yet...

On Fri, Jun 10, 2016 at 9:51 PM, aniljava notifications@github.com wrote:

> I tested Tested cnnPlayerMCTSV2.lua on 750 Ti, it responded normally upto
> 6 moves, after that it stopped responding and started freezing computer.
> 
> Also, when using cnnPlayerMCTSV2.lua with gogui, the debug messages with
> line ends, i think interferes with the GTP protocol triggering the timeout
> on the gogui.
> 
> A guide on GTP setup and expected system requirement would be nice.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/facebookresearch/darkforestGo/issues/3, or mute the
> thread
> https://github.com/notifications/unsubscribe/AC1g8UVsrGktbomRt8H5FzVHv_58QlDxks5qKj7VgaJpZM4IzeIJ
> .

## 

---

Yuandong Tian
Research Scientist,
Facebook Artificial Intelligence Research (FAIR)
Website:
https://research.facebook.com/researchers/1517678171821436/yuandong-tian/

**Comment by aniljava** [comment]
I am using single GPU. 

It is working now after removing all debug messages board dumps and recompiling. .c codes are printing to STDOUT instead of STDERR causing problem with GTP, after manually commenting out the printf from .c and .lua codes, it is working as expected with gogui.

I have not checked how instances are created for games, i think last time, i might had multiple instance running after CTRL+C on cnnPlayer. `killall luajit` and restarting the cnn_evaluator and `cnnPlayerMCTSV2.lua` solved the problem.

**Comment by soumith** [comment]
awesome! glad this is solved now.
